### ISSUE TITLE
Don't hard code /login redirect

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-react-components#110]
https://github.com/inrupt/solid-react-components/blob/65b5f7f394f13cf1ae3b1f86abe7e2feb494c76a/src/lib/components/withAuthorization/with-authorization.component.js#L13

I wanted a UI where you stay at the same domain until you log in, but I can't do that now :(

**Comment by james-martin-jd** [comment]
There are two layouts used in the generator application, public and private layout. 

The withAuthorization component is an optional component that enforces an authorized page. For example, if you have a dashboard that makes no sense to view without a logged in user, you can use the withAuthorization to block the user from viewing it without authorization.

This control is exposed in the generator via the layouts. The `private-layout` is a page template that authorized pages can use which includes the withAuthorization control, whereas `public-layout` is a page template that anyone can view whether they are logged in or not. Examples of public pages in the generator are the login page and /404, whereas the profile and welcome pages (and now game) are using the private layout since you need to be authenticated to have any real sort of interaction with those pages.
